Search.appendIndex(
    [
                {
            "fqsen": "\\Show_Diagram\u0028\u0029",
            "name": "Show_Diagram",
            "summary": "Summary.",
            "url": "namespaces/default.html#function_Show_Diagram"
        },                {
            "fqsen": "\\read_dir_content\u0028\u0029",
            "name": "read_dir_content",
            "summary": "",
            "url": "namespaces/default.html#function_read_dir_content"
        },                {
            "fqsen": "\\read_dir\u0028\u0029",
            "name": "read_dir",
            "summary": "",
            "url": "namespaces/default.html#function_read_dir"
        },                {
            "fqsen": "\\read_dir_stats\u0028\u0029",
            "name": "read_dir_stats",
            "summary": "",
            "url": "namespaces/default.html#function_read_dir_stats"
        },                {
            "fqsen": "\\read_dir_content_stats\u0028\u0029",
            "name": "read_dir_content_stats",
            "summary": "",
            "url": "namespaces/default.html#function_read_dir_content_stats"
        },                {
            "fqsen": "\\Show_options\u0028\u0029",
            "name": "Show_options",
            "summary": "",
            "url": "namespaces/default.html#function_Show_options"
        },                {
            "fqsen": "\\File_stats\u0028\u0029",
            "name": "File_stats",
            "summary": "",
            "url": "namespaces/default.html#function_File_stats"
        },                {
            "fqsen": "\\treeview",
            "name": "treeview",
            "summary": "",
            "url": "classes/treeview.html"
        },                {
            "fqsen": "\\treeview\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/treeview.html#method___construct"
        },                {
            "fqsen": "\\treeview\u003A\u003Acreate_tree\u0028\u0029",
            "name": "create_tree",
            "summary": "",
            "url": "classes/treeview.html#method_create_tree"
        },                {
            "fqsen": "\\treeview\u003A\u003A\u0024files",
            "name": "files",
            "summary": "",
            "url": "classes/treeview.html#property_files"
        },                {
            "fqsen": "\\treeview\u003A\u003A\u0024folder",
            "name": "folder",
            "summary": "",
            "url": "classes/treeview.html#property_folder"
        },                {
            "fqsen": "\\example\u0028\u0029",
            "name": "example",
            "summary": "Summary.",
            "url": "namespaces/default.html#function_example"
        },                {
            "fqsen": "\\getWorkdays\u0028\u0029",
            "name": "getWorkdays",
            "summary": "Count\u0020the\u0020number\u0020of\u0020working\u0020days\u0020between\u0020two\u0020dates.",
            "url": "namespaces/default.html#function_getWorkdays"
        },                {
            "fqsen": "\\start_clean_page\u0028\u0029",
            "name": "start_clean_page",
            "summary": "",
            "url": "namespaces/default.html#function_start_clean_page"
        },                {
            "fqsen": "\\start_page\u0028\u0029",
            "name": "start_page",
            "summary": "",
            "url": "namespaces/default.html#function_start_page"
        },                {
            "fqsen": "\\close_page\u0028\u0029",
            "name": "close_page",
            "summary": "",
            "url": "namespaces/default.html#function_close_page"
        },                {
            "fqsen": "\\Progress_bar\u0028\u0029",
            "name": "Progress_bar",
            "summary": "",
            "url": "namespaces/default.html#function_Progress_bar"
        },                {
            "fqsen": "\\Progress_bar_print\u0028\u0029",
            "name": "Progress_bar_print",
            "summary": "",
            "url": "namespaces/default.html#function_Progress_bar_print"
        },                {
            "fqsen": "\\Panel_toolbox\u0028\u0029",
            "name": "Panel_toolbox",
            "summary": "",
            "url": "namespaces/default.html#function_Panel_toolbox"
        },                {
            "fqsen": "\\Create_modal\u0028\u0029",
            "name": "Create_modal",
            "summary": "",
            "url": "namespaces/default.html#function_Create_modal"
        },                {
            "fqsen": "\\Get_Schools\u0028\u0029",
            "name": "Get_Schools",
            "summary": "",
            "url": "namespaces/default.html#function_Get_Schools"
        },                {
            "fqsen": "\\Get_School_Names\u0028\u0029",
            "name": "Get_School_Names",
            "summary": "",
            "url": "namespaces/default.html#function_Get_School_Names"
        },                {
            "fqsen": "\\Get_Snapshot_Students\u0028\u0029",
            "name": "Get_Snapshot_Students",
            "summary": "",
            "url": "namespaces/default.html#function_Get_Snapshot_Students"
        },                {
            "fqsen": "\\Get_EntryDates\u0028\u0029",
            "name": "Get_EntryDates",
            "summary": "",
            "url": "namespaces/default.html#function_Get_EntryDates"
        },                {
            "fqsen": "\\Get_Teachers\u0028\u0029",
            "name": "Get_Teachers",
            "summary": "",
            "url": "namespaces/default.html#function_Get_Teachers"
        },                {
            "fqsen": "\\Show_derror\u0028\u0029",
            "name": "Show_derror",
            "summary": "",
            "url": "namespaces/default.html#function_Show_derror"
        },                {
            "fqsen": "\\Get_File_Date\u0028\u0029",
            "name": "Get_File_Date",
            "summary": "",
            "url": "namespaces/default.html#function_Get_File_Date"
        },                {
            "fqsen": "\\Check_Security\u0028\u0029",
            "name": "Check_Security",
            "summary": "",
            "url": "namespaces/default.html#function_Check_Security"
        },                {
            "fqsen": "\\Snapshot_Retention\u0028\u0029",
            "name": "Snapshot_Retention",
            "summary": "",
            "url": "namespaces/default.html#function_Snapshot_Retention"
        },                {
            "fqsen": "\\Get_Esl_Students\u0028\u0029",
            "name": "Get_Esl_Students",
            "summary": "",
            "url": "namespaces/default.html#function_Get_Esl_Students"
        },                {
            "fqsen": "\\Get_Sped_Students\u0028\u0029",
            "name": "Get_Sped_Students",
            "summary": "",
            "url": "namespaces/default.html#function_Get_Sped_Students"
        },                {
            "fqsen": "\\Get_504_Students\u0028\u0029",
            "name": "Get_504_Students",
            "summary": "",
            "url": "namespaces/default.html#function_Get_504_Students"
        },                {
            "fqsen": "\\Graph_Perc\u0028\u0029",
            "name": "Graph_Perc",
            "summary": "",
            "url": "namespaces/default.html#function_Graph_Perc"
        },                {
            "fqsen": "\\Graph_Bar\u0028\u0029",
            "name": "Graph_Bar",
            "summary": "",
            "url": "namespaces/default.html#function_Graph_Bar"
        },                {
            "fqsen": "\\Graph_Pie\u0028\u0029",
            "name": "Graph_Pie",
            "summary": "",
            "url": "namespaces/default.html#function_Graph_Pie"
        },                {
            "fqsen": "\\Graph_Pie_1\u0028\u0029",
            "name": "Graph_Pie_1",
            "summary": "",
            "url": "namespaces/default.html#function_Graph_Pie_1"
        },                {
            "fqsen": "\\LineNumGraph\u0028\u0029",
            "name": "LineNumGraph",
            "summary": "",
            "url": "namespaces/default.html#function_LineNumGraph"
        },                {
            "fqsen": "\\Print_Line_Graph_Js\u0028\u0029",
            "name": "Print_Line_Graph_Js",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Line_Graph_Js"
        },                {
            "fqsen": "\\Table_header_lib\u0028\u0029",
            "name": "Table_header_lib",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header_lib"
        },                {
            "fqsen": "\\Table_header_students\u0028\u0029",
            "name": "Table_header_students",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header_students"
        },                {
            "fqsen": "\\Table_header_snapshots\u0028\u0029",
            "name": "Table_header_snapshots",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header_snapshots"
        },                {
            "fqsen": "\\Table_header_students_full\u0028\u0029",
            "name": "Table_header_students_full",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header_students_full"
        },                {
            "fqsen": "\\Table_footer_lib\u0028\u0029",
            "name": "Table_footer_lib",
            "summary": "",
            "url": "namespaces/default.html#function_Table_footer_lib"
        },                {
            "fqsen": "\\Open_Panel\u0028\u0029",
            "name": "Open_Panel",
            "summary": "",
            "url": "namespaces/default.html#function_Open_Panel"
        },                {
            "fqsen": "\\Close_panel\u0028\u0029",
            "name": "Close_panel",
            "summary": "",
            "url": "namespaces/default.html#function_Close_panel"
        },                {
            "fqsen": "\\String_exists\u0028\u0029",
            "name": "String_exists",
            "summary": "",
            "url": "namespaces/default.html#function_String_exists"
        },                {
            "fqsen": "\\Print_HelpModal\u0028\u0029",
            "name": "Print_HelpModal",
            "summary": "",
            "url": "namespaces/default.html#function_Print_HelpModal"
        },                {
            "fqsen": "\\Print_Assessment\u0028\u0029",
            "name": "Print_Assessment",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Assessment"
        },                {
            "fqsen": "\\SpecialPrograms\u0028\u0029",
            "name": "SpecialPrograms",
            "summary": "",
            "url": "namespaces/default.html#function_SpecialPrograms"
        },                {
            "fqsen": "\\OtherPrograms\u0028\u0029",
            "name": "OtherPrograms",
            "summary": "",
            "url": "namespaces/default.html#function_OtherPrograms"
        },                {
            "fqsen": "\\LineTimeGraph\u0028\u0029",
            "name": "LineTimeGraph",
            "summary": "",
            "url": "namespaces/default.html#function_LineTimeGraph"
        },                {
            "fqsen": "\\Schedule\u0028\u0029",
            "name": "Schedule",
            "summary": "",
            "url": "namespaces/default.html#function_Schedule"
        },                {
            "fqsen": "\\GenderMale\u0028\u0029",
            "name": "GenderMale",
            "summary": "",
            "url": "namespaces/default.html#function_GenderMale"
        },                {
            "fqsen": "\\GenderFemale\u0028\u0029",
            "name": "GenderFemale",
            "summary": "",
            "url": "namespaces/default.html#function_GenderFemale"
        },                {
            "fqsen": "\\HbarGrap\u0028\u0029",
            "name": "HbarGrap",
            "summary": "",
            "url": "namespaces/default.html#function_HbarGrap"
        },                {
            "fqsen": "\\DashGauge\u0028\u0029",
            "name": "DashGauge",
            "summary": "",
            "url": "namespaces/default.html#function_DashGauge"
        },                {
            "fqsen": "\\Print_Enrollments\u0028\u0029",
            "name": "Print_Enrollments",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Enrollments"
        },                {
            "fqsen": "\\Print_Schedule\u0028\u0029",
            "name": "Print_Schedule",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Schedule"
        },                {
            "fqsen": "\\Print_SpecialPrograms\u0028\u0029",
            "name": "Print_SpecialPrograms",
            "summary": "",
            "url": "namespaces/default.html#function_Print_SpecialPrograms"
        },                {
            "fqsen": "\\Print_OtherPrograms\u0028\u0029",
            "name": "Print_OtherPrograms",
            "summary": "",
            "url": "namespaces/default.html#function_Print_OtherPrograms"
        },                {
            "fqsen": "\\Print_YTD\u0028\u0029",
            "name": "Print_YTD",
            "summary": "",
            "url": "namespaces/default.html#function_Print_YTD"
        },                {
            "fqsen": "\\Print_ADA\u0028\u0029",
            "name": "Print_ADA",
            "summary": "",
            "url": "namespaces/default.html#function_Print_ADA"
        },                {
            "fqsen": "\\Print_Students\u0028\u0029",
            "name": "Print_Students",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Students"
        },                {
            "fqsen": "\\Print_School\u0028\u0029",
            "name": "Print_School",
            "summary": "",
            "url": "namespaces/default.html#function_Print_School"
        },                {
            "fqsen": "\\Print_Multi_Line_Graph_Js\u0028\u0029",
            "name": "Print_Multi_Line_Graph_Js",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Multi_Line_Graph_Js"
        },                {
            "fqsen": "\\Get_District_Stats\u0028\u0029",
            "name": "Get_District_Stats",
            "summary": "",
            "url": "namespaces/default.html#function_Get_District_Stats"
        },                {
            "fqsen": "\\Historical_Options\u0028\u0029",
            "name": "Historical_Options",
            "summary": "",
            "url": "namespaces/default.html#function_Historical_Options"
        },                {
            "fqsen": "\\Create_School_Checkbox\u0028\u0029",
            "name": "Create_School_Checkbox",
            "summary": "",
            "url": "namespaces/default.html#function_Create_School_Checkbox"
        },                {
            "fqsen": "\\Print_Student_Information\u0028\u0029",
            "name": "Print_Student_Information",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Student_Information"
        },                {
            "fqsen": "\\Print_Graph_Js\u0028\u0029",
            "name": "Print_Graph_Js",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Graph_Js"
        },                {
            "fqsen": "\\Table_Assessment_header\u0028\u0029",
            "name": "Table_Assessment_header",
            "summary": "",
            "url": "namespaces/default.html#function_Table_Assessment_header"
        },                {
            "fqsen": "\\Table_Closed_header\u0028\u0029",
            "name": "Table_Closed_header",
            "summary": "",
            "url": "namespaces/default.html#function_Table_Closed_header"
        },                {
            "fqsen": "\\Table_Progress_header\u0028\u0029",
            "name": "Table_Progress_header",
            "summary": "",
            "url": "namespaces/default.html#function_Table_Progress_header"
        },                {
            "fqsen": "\\Table_header\u0028\u0029",
            "name": "Table_header",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header"
        },                {
            "fqsen": "\\Table_footer\u0028\u0029",
            "name": "Table_footer",
            "summary": "",
            "url": "namespaces/default.html#function_Table_footer"
        },                {
            "fqsen": "\\Print_Pie_Graph_Js\u0028\u0029",
            "name": "Print_Pie_Graph_Js",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Pie_Graph_Js"
        },                {
            "fqsen": "\\Print_Bar_Graph_Js\u0028\u0029",
            "name": "Print_Bar_Graph_Js",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Bar_Graph_Js"
        },                {
            "fqsen": "\\Table_header_course\u0028\u0029",
            "name": "Table_header_course",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header_course"
        },                {
            "fqsen": "\\Table_header_subject\u0028\u0029",
            "name": "Table_header_subject",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header_subject"
        },                {
            "fqsen": "\\Table_header_school\u0028\u0029",
            "name": "Table_header_school",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header_school"
        },                {
            "fqsen": "\\Print_Options\u0028\u0029",
            "name": "Print_Options",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Options"
        },                {
            "fqsen": "\\Print_Missing\u0028\u0029",
            "name": "Print_Missing",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Missing"
        },                {
            "fqsen": "\\Print_Progress\u0028\u0029",
            "name": "Print_Progress",
            "summary": "",
            "url": "namespaces/default.html#function_Print_Progress"
        },                {
            "fqsen": "\\Table_header_Classrooms\u0028\u0029",
            "name": "Table_header_Classrooms",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header_Classrooms"
        },                {
            "fqsen": "\\Table_header_Courses\u0028\u0029",
            "name": "Table_header_Courses",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header_Courses"
        },                {
            "fqsen": "\\Table_header_Std\u0028\u0029",
            "name": "Table_header_Std",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header_Std"
        },                {
            "fqsen": "\\Table_header_Credits\u0028\u0029",
            "name": "Table_header_Credits",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header_Credits"
        },                {
            "fqsen": "\\Table_header_Roster\u0028\u0029",
            "name": "Table_header_Roster",
            "summary": "",
            "url": "namespaces/default.html#function_Table_header_Roster"
        },                {
            "fqsen": "\\Table_YTD_header\u0028\u0029",
            "name": "Table_YTD_header",
            "summary": "",
            "url": "namespaces/default.html#function_Table_YTD_header"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
